#!/bin/bash
HERE=$(cd "$(dirname "$0")";pwd)

VERSION=20180408
echo "QQ appimage was made in $VERSION"

if [ $EUID -eq 0 ]; then
    echo "Please not run QQ as root. Please run it without sudo"
    exit 1
fi

RO_DATADIR="$HERE/Deepin-QQ/"
export RW_DATADIR="$HOME/.DeepinQQ.unionfs"
mkdir -p $RW_DATADIR $HOME/.DeepinQQ.Appimage
$HERE/usr/bin/unionfs-fuse -o use_ino,nonempty,uid=$UID -o cow "$HOME/.DeepinQQ.Appimage"=RW:"$RO_DATADIR"=RO "$RW_DATADIR" || exit 1 #处理QQ运行产生的数据

if [ $(cat /proc/sys/kernel/unprivileged_userns_clone) == "1" ]; then
	unshare -mr  $HERE/runqq
else
	$HERE/runqq-proot
fi

function finish {
  echo "Cleaning up"
  killall $HERE/usr/bin/unionfs-fuse
}
trap finish EXIT
